//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GusInfo.Service {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParametryWyszukiwania", Namespace="http://CIS/BIR/PUBL/2014/07/DataContract")]
    [System.SerializableAttribute()]
    public partial class ParametryWyszukiwania : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KrsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KrsyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NipyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Regony14znField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Regony9znField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Krs {
            get {
                return this.KrsField;
            }
            set {
                if ((object.ReferenceEquals(this.KrsField, value) != true)) {
                    this.KrsField = value;
                    this.RaisePropertyChanged("Krs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Krsy {
            get {
                return this.KrsyField;
            }
            set {
                if ((object.ReferenceEquals(this.KrsyField, value) != true)) {
                    this.KrsyField = value;
                    this.RaisePropertyChanged("Krsy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nip {
            get {
                return this.NipField;
            }
            set {
                if ((object.ReferenceEquals(this.NipField, value) != true)) {
                    this.NipField = value;
                    this.RaisePropertyChanged("Nip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nipy {
            get {
                return this.NipyField;
            }
            set {
                if ((object.ReferenceEquals(this.NipyField, value) != true)) {
                    this.NipyField = value;
                    this.RaisePropertyChanged("Nipy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Regon {
            get {
                return this.RegonField;
            }
            set {
                if ((object.ReferenceEquals(this.RegonField, value) != true)) {
                    this.RegonField = value;
                    this.RaisePropertyChanged("Regon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Regony14zn {
            get {
                return this.Regony14znField;
            }
            set {
                if ((object.ReferenceEquals(this.Regony14znField, value) != true)) {
                    this.Regony14znField = value;
                    this.RaisePropertyChanged("Regony14zn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Regony9zn {
            get {
                return this.Regony9znField;
            }
            set {
                if ((object.ReferenceEquals(this.Regony9znField, value) != true)) {
                    this.Regony9znField = value;
                    this.RaisePropertyChanged("Regony9zn");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://CIS/BIR/PUBL/2014/07", ConfigurationName="Service.IUslugaBIRzewnPubl")]
    public interface IUslugaBIRzewnPubl {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://CIS/BIR/2014/07) of message PobierzCaptchaRequest does not match the default value (http://CIS/BIR/PUBL/2014/07)
        [System.ServiceModel.OperationContractAttribute(Action="http://CIS/BIR/2014/07/IUslugaBIR/PobierzCaptcha", ReplyAction="http://CIS/BIR/2014/07/IUslugaBIR/PobierzCaptchaResponse")]
        GusInfo.Service.PobierzCaptchaResponse PobierzCaptcha(GusInfo.Service.PobierzCaptchaRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://CIS/BIR/2014/07) of message SprawdzCaptchaRequest does not match the default value (http://CIS/BIR/PUBL/2014/07)
        [System.ServiceModel.OperationContractAttribute(Action="http://CIS/BIR/2014/07/IUslugaBIR/SprawdzCaptcha", ReplyAction="http://CIS/BIR/2014/07/IUslugaBIR/SprawdzCaptchaResponse")]
        GusInfo.Service.SprawdzCaptchaResponse SprawdzCaptcha(GusInfo.Service.SprawdzCaptchaRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://CIS/BIR/2014/07) of message SetValueRequest does not match the default value (http://CIS/BIR/PUBL/2014/07)
        [System.ServiceModel.OperationContractAttribute(Action="http://CIS/BIR/2014/07/IUslugaBIR/SetValue", ReplyAction="http://CIS/BIR/2014/07/IUslugaBIR/SetValueResponse")]
        GusInfo.Service.SetValueResponse SetValue(GusInfo.Service.SetValueRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://CIS/BIR/2014/07) of message GetValueRequest does not match the default value (http://CIS/BIR/PUBL/2014/07)
        [System.ServiceModel.OperationContractAttribute(Action="http://CIS/BIR/2014/07/IUslugaBIR/GetValue", ReplyAction="http://CIS/BIR/2014/07/IUslugaBIR/GetValueResponse")]
        GusInfo.Service.GetValueResponse GetValue(GusInfo.Service.GetValueRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CIS/BIR/PUBL/2014/07/IUslugaBIRzewnPubl/Zaloguj", ReplyAction="http://CIS/BIR/PUBL/2014/07/IUslugaBIRzewnPubl/ZalogujResponse")]
        string Zaloguj(string pKluczUzytkownika);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CIS/BIR/PUBL/2014/07/IUslugaBIRzewnPubl/Wyloguj", ReplyAction="http://CIS/BIR/PUBL/2014/07/IUslugaBIRzewnPubl/WylogujResponse")]
        bool Wyloguj(string pIdentyfikatorSesji);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CIS/BIR/PUBL/2014/07/IUslugaBIRzewnPubl/DaneSzukaj", ReplyAction="http://CIS/BIR/PUBL/2014/07/IUslugaBIRzewnPubl/DaneSzukajResponse")]
        string DaneSzukaj(GusInfo.Service.ParametryWyszukiwania pParametryWyszukiwania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CIS/BIR/PUBL/2014/07/IUslugaBIRzewnPubl/DanePobierzPelnyRaport", ReplyAction="http://CIS/BIR/PUBL/2014/07/IUslugaBIRzewnPubl/DanePobierzPelnyRaportResponse")]
        string DanePobierzPelnyRaport(string pRegon, string pNazwaRaportu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CIS/BIR/PUBL/2014/07/IUslugaBIRzewnPubl/DaneKomunikat", ReplyAction="http://CIS/BIR/PUBL/2014/07/IUslugaBIRzewnPubl/DaneKomunikatResponse")]
        string DaneKomunikat();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PobierzCaptcha", WrapperNamespace="http://CIS/BIR/2014/07", IsWrapped=true)]
    public partial class PobierzCaptchaRequest {
        
        public PobierzCaptchaRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PobierzCaptchaResponse", WrapperNamespace="http://CIS/BIR/2014/07", IsWrapped=true)]
    public partial class PobierzCaptchaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CIS/BIR/2014/07", Order=0)]
        public string PobierzCaptchaResult;
        
        public PobierzCaptchaResponse() {
        }
        
        public PobierzCaptchaResponse(string PobierzCaptchaResult) {
            this.PobierzCaptchaResult = PobierzCaptchaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SprawdzCaptcha", WrapperNamespace="http://CIS/BIR/2014/07", IsWrapped=true)]
    public partial class SprawdzCaptchaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CIS/BIR/2014/07", Order=0)]
        public string pCaptcha;
        
        public SprawdzCaptchaRequest() {
        }
        
        public SprawdzCaptchaRequest(string pCaptcha) {
            this.pCaptcha = pCaptcha;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SprawdzCaptchaResponse", WrapperNamespace="http://CIS/BIR/2014/07", IsWrapped=true)]
    public partial class SprawdzCaptchaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CIS/BIR/2014/07", Order=0)]
        public bool SprawdzCaptchaResult;
        
        public SprawdzCaptchaResponse() {
        }
        
        public SprawdzCaptchaResponse(bool SprawdzCaptchaResult) {
            this.SprawdzCaptchaResult = SprawdzCaptchaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetValue", WrapperNamespace="http://CIS/BIR/2014/07", IsWrapped=true)]
    public partial class SetValueRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CIS/BIR/2014/07", Order=0)]
        public string pNazwaParametru;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CIS/BIR/2014/07", Order=1)]
        public string pWartoscParametru;
        
        public SetValueRequest() {
        }
        
        public SetValueRequest(string pNazwaParametru, string pWartoscParametru) {
            this.pNazwaParametru = pNazwaParametru;
            this.pWartoscParametru = pWartoscParametru;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetValueResponse", WrapperNamespace="http://CIS/BIR/2014/07", IsWrapped=true)]
    public partial class SetValueResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CIS/BIR/2014/07", Order=0)]
        public string SetValueResult;
        
        public SetValueResponse() {
        }
        
        public SetValueResponse(string SetValueResult) {
            this.SetValueResult = SetValueResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetValue", WrapperNamespace="http://CIS/BIR/2014/07", IsWrapped=true)]
    public partial class GetValueRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CIS/BIR/2014/07", Order=0)]
        public string pNazwaParametru;
        
        public GetValueRequest() {
        }
        
        public GetValueRequest(string pNazwaParametru) {
            this.pNazwaParametru = pNazwaParametru;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetValueResponse", WrapperNamespace="http://CIS/BIR/2014/07", IsWrapped=true)]
    public partial class GetValueResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CIS/BIR/2014/07", Order=0)]
        public string GetValueResult;
        
        public GetValueResponse() {
        }
        
        public GetValueResponse(string GetValueResult) {
            this.GetValueResult = GetValueResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUslugaBIRzewnPublChannel : GusInfo.Service.IUslugaBIRzewnPubl, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UslugaBIRzewnPublClient : System.ServiceModel.ClientBase<GusInfo.Service.IUslugaBIRzewnPubl>, GusInfo.Service.IUslugaBIRzewnPubl {
        
        public UslugaBIRzewnPublClient() {
        }
        
        public UslugaBIRzewnPublClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UslugaBIRzewnPublClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UslugaBIRzewnPublClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UslugaBIRzewnPublClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GusInfo.Service.PobierzCaptchaResponse GusInfo.Service.IUslugaBIRzewnPubl.PobierzCaptcha(GusInfo.Service.PobierzCaptchaRequest request) {
            return base.Channel.PobierzCaptcha(request);
        }
        
        public string PobierzCaptcha() {
            GusInfo.Service.PobierzCaptchaRequest inValue = new GusInfo.Service.PobierzCaptchaRequest();
            GusInfo.Service.PobierzCaptchaResponse retVal = ((GusInfo.Service.IUslugaBIRzewnPubl)(this)).PobierzCaptcha(inValue);
            return retVal.PobierzCaptchaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GusInfo.Service.SprawdzCaptchaResponse GusInfo.Service.IUslugaBIRzewnPubl.SprawdzCaptcha(GusInfo.Service.SprawdzCaptchaRequest request) {
            return base.Channel.SprawdzCaptcha(request);
        }
        
        public bool SprawdzCaptcha(string pCaptcha) {
            GusInfo.Service.SprawdzCaptchaRequest inValue = new GusInfo.Service.SprawdzCaptchaRequest();
            inValue.pCaptcha = pCaptcha;
            GusInfo.Service.SprawdzCaptchaResponse retVal = ((GusInfo.Service.IUslugaBIRzewnPubl)(this)).SprawdzCaptcha(inValue);
            return retVal.SprawdzCaptchaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GusInfo.Service.SetValueResponse GusInfo.Service.IUslugaBIRzewnPubl.SetValue(GusInfo.Service.SetValueRequest request) {
            return base.Channel.SetValue(request);
        }
        
        public string SetValue(string pNazwaParametru, string pWartoscParametru) {
            GusInfo.Service.SetValueRequest inValue = new GusInfo.Service.SetValueRequest();
            inValue.pNazwaParametru = pNazwaParametru;
            inValue.pWartoscParametru = pWartoscParametru;
            GusInfo.Service.SetValueResponse retVal = ((GusInfo.Service.IUslugaBIRzewnPubl)(this)).SetValue(inValue);
            return retVal.SetValueResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GusInfo.Service.GetValueResponse GusInfo.Service.IUslugaBIRzewnPubl.GetValue(GusInfo.Service.GetValueRequest request) {
            return base.Channel.GetValue(request);
        }
        
        public string GetValue(string pNazwaParametru) {
            GusInfo.Service.GetValueRequest inValue = new GusInfo.Service.GetValueRequest();
            inValue.pNazwaParametru = pNazwaParametru;
            GusInfo.Service.GetValueResponse retVal = ((GusInfo.Service.IUslugaBIRzewnPubl)(this)).GetValue(inValue);
            return retVal.GetValueResult;
        }
        
        public string Zaloguj(string pKluczUzytkownika) {
            return base.Channel.Zaloguj(pKluczUzytkownika);
        }
        
        public bool Wyloguj(string pIdentyfikatorSesji) {
            return base.Channel.Wyloguj(pIdentyfikatorSesji);
        }
        
        public string DaneSzukaj(GusInfo.Service.ParametryWyszukiwania pParametryWyszukiwania) {
            return base.Channel.DaneSzukaj(pParametryWyszukiwania);
        }
        
        public string DanePobierzPelnyRaport(string pRegon, string pNazwaRaportu) {
            return base.Channel.DanePobierzPelnyRaport(pRegon, pNazwaRaportu);
        }
        
        public string DaneKomunikat() {
            return base.Channel.DaneKomunikat();
        }
    }
}
